version: '3.5'

services:

  app:
    image: likesistemas/sistema-core:${VERSAO:-latest}-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
      - IMAGE=${IMAGE:-sistema-core}
      - VERSAO=${VERSAO:-latest}
      - VERSAO_BUILD=${VERSAO_BUILD:-latest}
      - PASTA_WWW=${PASTA_WWW:-www73}
    volumes:
    - www:/var/www/
    - /var/src/
    environment:
    - INSTALL_COMPOSER=false
    - COMPOSER_INSTALL=false
  
  nginx:
    volumes:
    - www:/var/www/

volumes:
  www: