version: '3.5'

services:

    app:
      image: likesistemas/sistema-core-dev:80
      environment: 
        - INSTALL_COMPOSER=false
      build:
        context: .
        args:
          - VERSAO_PHP=likesistemas/php-dev:80