version: '3.5'
networks: 
    lemp:
        name: lemp
        driver: bridge

services:

    app:
        build:
            context: .
            args:
            - VERSAO_PHP=likesistemas/php:80
        image: likesistemas/sistema-core:80-dev
        container_name: app
        command: app create && add-new-config php version 8.0
        environment:
            - PHP_NAME=lemp
            - APP_NAME=app
            - DB_HOST=mysql
            - DB_USER=root
            - DB_PASSWORD=123456
            - DB_NAME=php
            - DB_HOST_SLAVE=mysql_slave
            - MEMCACHE_HOST=memcache
            - MEMCACHE_PORT=11212
            - EMAIL_USUARIO=core@likesistemas.com.br
            - EMAIL_SENHA=123456
            - EMAIL_NOME=Ricardo
            - AWS_KEY=like123456
            - AWS_SECRET=78910
            - INSTALL_COMPOSER=true
            - COMPOSER_INSTALL=true
            - DB_MIGRATE=true
        volumes:
            - ./www80/:/var/src/
        networks:
            - lemp
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: mysql:5.5
        command: --innodb-use-native-aio=0
        volumes:
            - core-mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=php
        networks:
            - lemp

    nginx:
        image: likesistemas/nginx:latest
        container_name: core_nginx
        restart: on-failure
        environment:
            - HOST_PHP=app
            - PORTA_PHP=9000
            - INDEX_FILE=index.php
        ports:
            - 80:80
        volumes:
            - ./www80/:/var/www/
        links:
            - app
        depends_on:
            - app
        networks:
            - lemp

volumes:
    core-mysql-data: