services:

    app:
      image: likesistemas/sistema-core-dev:${PHP_VERSION}-dev
      environment: 
        - INSTALL_COMPOSER=false
      build:
        context: .
        args:
          - VERSAO_PHP=likesistemas/php-dev:${PHP_VERSION}