#!/bin/bash

source php-utils

CONFIG_HOME=$(get_filename_home ${ARQUIVO_CONFIG})
SRC_ARQUIVO_CONFIG="${CONFIG_HOME}/${ARQUIVO_CONFIG}"

if [ -f "${SRC_ARQUIVO_CONFIG}" ] && [ -n "$DB_HOST" ]; then
	if [ -z $DB_TYPE ]; then
		DB_TYPE='ini';
	fi

	set-own ${SRC_ARQUIVO_CONFIG}

	if [ "$DB_TYPE" = "ini" ]; then
		configure-db-ini ${SRC_ARQUIVO_CONFIG}
	else
		configure-db-tstore ${SRC_ARQUIVO_CONFIG}
	fi
else
	if [ ! -f "${SRC_ARQUIVO_CONFIG}" ]; then
		echo "config-db: Arquivo '${SRC_ARQUIVO_CONFIG}' não existe.";
	else
		echo "config-db: Não foi informado host '${DB_HOST}'.";
	fi
fi