#!/bin/bash

echo "Configurando arquivo e configuração..."
crudini --set ${1} bd host ${DB_HOST};
crudini --set ${1} bd user ${DB_USER};
crudini --set ${1} bd password ${DB_PASSWORD};
crudini --set ${1} bd bd ${DB_NAME};

if [ -n "$SOCKET_HOST" ]; then
	crudini --set ${1} socket host ${SOCKET_HOST};
fi