#!/bin/bash

source php-utils

VOLUME_HOME=$(get_filename_home ${ARQUIVO_CONFIG})

echo "Criando volumes na pasta '${VOLUME_HOME}'...";
cd ${VOLUME_HOME}

VOLUMES_ARRAY=(${VOLUMES})

for i in "${VOLUMES_ARRAY[@]}"
do
  :
  new-folder ${i}
done

echo ""
tree -L 2 -d
echo ""
