#!/bin/bash

ARQUIVO_APP="${PUBLIC_HTML}/app";
ARQUIVO_PHP_APP="${PUBLIC_HTML}/app.php";

if [ -f "${ARQUIVO_APP}" ]; then
	echo "Configurando App '${1}'"
	chmod +x ${ARQUIVO_APP} ${ARQUIVO_PHP_APP}
	ln -s ${ARQUIVO_APP} /usr/local/bin/${1}
	chmod +x /usr/local/bin/${1}
fi;