#!/bin/bash

echo "Configurando o bd...";
sudo echo "if(!SiteConfig::hasDefinedBd()) { SiteConfig::setBd('${DB_HOST}','${DB_USER}','${DB_PASSWORD}','${DB_NAME}'); }" >> ${ARQUIVO_CONFIG};

if [ -n "$MEMCACHE_HOST" ]; then
	sudo echo "SiteConfig::setCacheMemcache('${MEMCACHE_HOST}','${MEMCACHE_PORT}');" >> ${ARQUIVO_CONFIG};
fi