#!/bin/bash

echo "Configurando arquivo e configuração..."
sudo crudini --set ${ARQUIVO_CONFIG} bd host ${DB_HOST};
sudo crudini --set ${ARQUIVO_CONFIG} bd user ${DB_USER};
sudo crudini --set ${ARQUIVO_CONFIG} bd password ${DB_PASSWORD};
sudo crudini --set ${ARQUIVO_CONFIG} bd bd ${DB_NAME};

if [ -n "$SOCKET_HOST" ]; then
	sudo crudini --set ${ARQUIVO_CONFIG} socket host ${SOCKET_HOST};
fi