#!/bin/bash

echo "Configurando arquivo e configuração..."
crudini --set ${1} bd host ${DB_HOST};
crudini --set ${1} bd user ${DB_USER};
crudini --set ${1} bd password ${DB_PASSWORD};
crudini --set ${1} bd bd ${DB_NAME};

if [ -n "$DB_HOST_SLAVE" ]; then
	crudini --set ${1} bd hostSlave ${DB_HOST_SLAVE};
fi

if [ -n "$SOCKET_HOST" ]; then
	crudini --set ${1} socket host ${SOCKET_HOST};
fi

if [ -n "$MEMCACHE_HOST" ]; then
	crudini --set ${1} session tipo memcache;
	crudini --set ${1} session dsnMemcache memcached://${MEMCACHE_HOST}:${MEMCACHE_PORT:-11211};
fi