#!/bin/bash

source php-utils

NOME_ARQUIVO_PHP="app.php"

if [ ! -n "${1}" ]; then
    DIR=$(cd "${0%[/\\]*}" > /dev/null; cd "./" && pwd)
    PHP_APP="${DIR}/${NOME_ARQUIVO_PHP}";
else
    PHP_APP="${1}";
fi

if [ ! -f "${PHP_APP}" ]; then
    CONFIG_HOME=$(get_filename_home ${NOME_ARQUIVO_PHP})
	PHP_APP="${CONFIG_HOME}/app.php";
fi

sudo -u www-data "${PHP_APP}" "$@"