#!/bin/bash

if [ -d "${SOURCE_CODE_FOLDER}/" ]; then
	if [ -n "${SOURCE_CODE_FOLDER_TO_COPY}" ]; then
		cp -r ${SOURCE_CODE_FOLDER}/. ${SOURCE_CODE_FOLDER_TO_COPY}/;
	else
		if [ -d "${SOURCE_CODE_FOLDER}/public/" ]; then
			cp -r ${SOURCE_CODE_FOLDER}/. ${WWW}/;
		else
			cp -r ${SOURCE_CODE_FOLDER}/. ${PUBLIC_HTML}/;
		fi
	fi	
fi

new-folder ${TEMP_FOLDER}
new-folder ${FILES_FOLDER}
new-folder ${LOGS_FOLDER}

new-folder "${TEMP_FOLDER}css/"
new-folder "${TEMP_FOLDER}js/"
new-folder "${TEMP_FOLDER}manifest/"
new-folder "${TEMP_FOLDER}object/"

configure-db;
configure-app ${APP_NAME};