#!/bin/bash

if [ -d "${SOURCE_CODE_FOLDER}/" ]; then
	cp -r ${SOURCE_CODE_FOLDER}/. ${PUBLIC_HTML}/;
fi

set-own ${TEMP_FOLDER}
set-own ${FILES_FOLDER}
set-own ${LOGS_FOLDER}

new-folder "${TEMP_FOLDER}/css/"
new-folder "${TEMP_FOLDER}/js/"
new-folder "${TEMP_FOLDER}/manifest/"
new-folder "${TEMP_FOLDER}/object/"

configure-db;
configure-app ${APP_NAME};