#!/bin/bash

if [ -d "${SOURCE_CODE_FOLDER}/" ]; then
	cp -r ${SOURCE_CODE_FOLDER}/. ${PUBLIC_HTML}/;
fi

new-folder ${TEMP_FOLDER}
new-folder ${FILES_FOLDER}
new-folder ${LOGS_FOLDER}

new-folder "${TEMP_FOLDER}/css/"
new-folder "${TEMP_FOLDER}/js/"
new-folder "${TEMP_FOLDER}/manifest/"
new-folder "${TEMP_FOLDER}/object/"

configure-db;
configure-app ${APP_NAME};