#!/usr/bin/env sh

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "./" && pwd)

if [ -d /proc/cygdrive ] && [[ $(which php) == $(readlink -n /proc/cygdrive)/* ]]; then
   # We are in Cgywin using Windows php, so the path must be translated
   dir=$(cygpath -m "$dir");
fi

phpapp="${dir}/app.php";
if [ ! -f "${phpapp}" ] && [ "${AMBIENTE}" = "producao" ]; then
	phpapp="/var/www/public/app.php";
fi

"${phpapp}" "$@"