name: PHP Dev

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  
  test:
    strategy:
      matrix:
        PHP: [56, 73, 74, 80]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare code
        env:
          PHP_VERSION: ${{ matrix.PHP }}
        run: |
          touch .env
          echo "IMAGE=sistema-core-dev" >> .env
          echo "VERSAO=${PHP_VERSION}-dev" >> .env
          echo "PASTA_WWW=www${PHP_VERSION}" >> .env

      - name: Run tests dev
        env:
          PHP_VERSION: ${{ matrix.PHP }}
        run: |
          docker-compose \
            --file docker-compose.yml \
            --file docker-compose-${PHP_VERSION}.yml \
            --file docker-compose-${PHP_VERSION}.dev.yml \
            up --build -d
          
          echo $(docker run -t --network lemp jwilder/dockerize \
            -wait http://core_nginx/ \
            -timeout 60s)

          docker ps -a
          docker logs app

          CONTENT=$(curl -s "http://127.0.0.1/");
          APP_CONTENT=$(docker exec app app echo);

          echo "CHAMADA HTTP: ${CONTENT}";
          echo "CHAMADA APP: ${APP_CONTENT}";

          if [ "${CONTENT}" != "core|${PHP_VERSION}" ]; then
            echo "Chamada HTTP retornou errado: ${CONTENT}"
            exit 1;
          fi

          if [ "${APP_CONTENT}" != "core|${PHP_VERSION}" ]; then
            echo "Chamada APP retornou errado: ${APP_CONTENT}"
            exit 1;
          fi

          docker-compose \
            --file docker-compose.yml \
            --file docker-compose-${PHP_VERSION}.yml \
            --file docker-compose-${PHP_VERSION}.dev.yml \
            down -v

      - name: Run tests prod
        env:
          PHP_VERSION: ${{ matrix.PHP }}
        run: |
          docker-compose \
            --file docker-compose.yml \
            --file docker-compose-${PHP_VERSION}.yml \
            --file docker-compose-${PHP_VERSION}.dev.yml \
            --file docker-compose.prod.yml \
            up --build -d
          
          echo $(docker run -t --network lemp jwilder/dockerize \
            -wait http://core_nginx/ \
            -timeout 60s)

          docker ps -a
          docker logs app

          CONTENT=$(curl -s "http://127.0.0.1/");
          APP_CONTENT=$(docker exec app app echo);

          echo "CHAMADA HTTP: ${CONTENT}";
          echo "CHAMADA APP: ${APP_CONTENT}";

          if [ "${CONTENT}" != "core|${PHP_VERSION}" ]; then
            echo "Chamada HTTP retornou errado: ${CONTENT}"
            exit 1;
          fi

          if [ "${APP_CONTENT}" != "core|${PHP_VERSION}" ]; then
            echo "Chamada APP retornou errado: ${APP_CONTENT}"
            exit 1;
          fi

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: PHP 5.6 -> Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VERSAO_PHP=likesistemas/php-dev:56
          push: true
          tags: |
            likesistemas/sistema-core-dev:56
            likesistemas/sistema-core-dev:5.6
            ghcr.io/likesistemas/sistema-core-dev:56
            ghcr.io/likesistemas/sistema-core-dev:5.6

      - name: PHP 7.3 -> Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VERSAO_PHP=likesistemas/php-dev:73
          push: true
          tags: |
            likesistemas/sistema-core-dev:latest
            likesistemas/sistema-core-dev:73
            likesistemas/sistema-core-dev:7.3
            ghcr.io/likesistemas/sistema-core-dev:latest
            ghcr.io/likesistemas/sistema-core-dev:73
            ghcr.io/likesistemas/sistema-core-dev:7.3

      - name: PHP 7.4 -> Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VERSAO_PHP=likesistemas/php-dev:74
          push: true
          tags: |
            likesistemas/sistema-core-dev:74
            likesistemas/sistema-core-dev:7.4
            ghcr.io/likesistemas/sistema-core-dev:74
            ghcr.io/likesistemas/sistema-core-dev:7.4
      
      - name: PHP 8.0 -> Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VERSAO_PHP=likesistemas/php-dev:80
          push: true
          tags: |
            likesistemas/sistema-core-dev:80
            likesistemas/sistema-core-dev:8.0
            ghcr.io/likesistemas/sistema-core-dev:80
            ghcr.io/likesistemas/sistema-core-dev:8.0