name: PHP 5.6 dev

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker-compose \
            --file docker-compose-56.yml \
            --file docker-compose-56.dev.yml \
            up --build -d
          
          docker run -t --network lemp56 jwilder/dockerize \
            -wait http://core56_nginx/ \
            -timeout 120s

          docker ps -a
          docker logs app56

          CONTENT=$(curl -s "http://127.0.0.1/");
          APP_CONTENT=$(docker exec app56 app echo);

          echo "CHAMADA HTTP: ${CONTENT}";
          echo "CHAMADA APP: ${APP_CONTENT}";

          if [ "${CONTENT}" != "core|56" ]; then
            echo "Chamada HTTP retornou errado: ${CONTENT}"
            exit 1;
          fi

          if [ "${APP_CONTENT}" != "core|56" ]; then
            echo "Chamada APP retornou errado: ${APP_CONTENT}"
            exit 1;
          fi

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: likesistemas/sistema-core-dev
          build_args: VERSAO_PHP=likesistemas/php-dev:56
          tags: 5.6,56
